url: https://y7kim.github.io
baseurl: /3dastro-website/

# Site settings
title: ASTROmakes
email: your-email@domain.com
description: "Works???"


# Team names, titles and social links
people:
- name: Arunas Mazeika
  pic: 1
  location: Nantes, France
  position: Husband and father of two wonderful kids.
  social:
    - title: github
      url: https://github.com/amazeika
      icon: fa-brands fa-github
    - title: x-twitter
      url: https://x.com/arunasmazeika
    - title: facebook
      url: https://www.facebook.com/amazeika
    - title: linkedin
      url: https://www.linkedin.com/in/arunasmazeika

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty